jwt:
  secret: (시크릿 키) # JWT 토큰을 서명할 때 사용할 시크릿 키
  token-validity-in-seconds: 3600 # 토큰 유효 기간
  refresh-token-validity-in-seconds: 86400 # 리프레시 토큰 유효 기간

spring:
  data:
    redis:
      host: localhost
      port: 6379